### ISSUE TITLE
MinDrawer script issue

### ISSUE THREAD

**Issue by 1azybones1** [Chman/Moments#24]
Assets\Moments Recorder\Scripts\Editor\MinDrawer.cs(30,31): error CS0104: 'MinAttribute' is an ambiguous reference between 'Moments.MinAttribute' and 'UnityEngine.MinAttribute'

I'm new to coding and got this issue while trying to open the Demo.

**Comment by randoomx8** [comment]
I saw you closed this, why? Did you find a solution?
